baseURL = 'https://guyclicking.github.io/book'
languageCode = 'en-us'
title = 'Blindfolded Solving'
theme = "hugo-book"
enableGitInfo = true
publishDir = "docs"

[params]

    BookTheme = 'auto'
    BookRepo = 'https://github.com/blders/book'
    BookCommitPath = 'commit'
    BookEditPath = 'blob/main'
